# triton-compose.yml - Run services on Triton
#

# Nginx as a load-balancing tier and reverse proxy, with caching and optional SSL termination
nginx:
    extends:
      file: common-services.yml
      service: nginx
    links:
        - consul
        - stashbox
    labels:
        - triton.cns.services=${COMPOSE_PROJECT_NAME}
    environment:
        - CONSUL_AGENT=1
        - CONSUL=consul-${COMPOSE_PROJECT_NAME}.svc.${TRITON_ACCOUNT}.${TRITON_DC}.cns.joyent.com

# The Synchro microservice
synchro:
    extends:
      file: common-services.yml
      service: synchro
    links:
        - redis
        - consul
        - stashbox
    environment:
        - CONSUL_AGENT=1
        - CONSUL=consul-${COMPOSE_PROJECT_NAME}.svc.${TRITON_ACCOUNT}.${TRITON_DC}.cns.joyent.com

# StashBox
stashbox:
    extends:
      file: common-services.yml
      service: stashbox

# redis
redis:
    extends:
      file: common-services.yml
      service: redis
    links:
        - consul
    environment:
        - CONSUL_AGENT=1
        - CONSUL=consul-${COMPOSE_PROJECT_NAME}.svc.${TRITON_ACCOUNT}.${TRITON_DC}.cns.joyent.com

# Prometheus performance monitoring
prometheus:
    extends:
      file: common-services.yml
      service: prometheus
    links:
        - consul
    labels:
        - triton.cns.services=prometheus-${COMPOSE_PROJECT_NAME}
    environment:
        - CONSUL_AGENT=1
        - CONSUL=consul-${COMPOSE_PROJECT_NAME}.svc.${TRITON_ACCOUNT}.${TRITON_DC}.cns.joyent.com

# service discovery tier
consul:
    extends:
      file: common-services.yml
      service: consul
    labels:
        - triton.cns.services=consul-${COMPOSE_PROJECT_NAME}
